version: '2'
services:
  web:
    build:
      context: .
      args:
       GIT_TOKEN: 3b9118a0a5b695c2ad9e914964e9180a37461634  
    depends_on:
      - db
    env_file:
      - .app.env
    links:
    - db:mysql
  db:
    image: mariadb
    environment:
      - MYSQL_DATABASE: db_name
      - MYSQL_USER: db_user
      - MYSQL_PASSWORD: db_pass
    volumes:
      - /databases/yfldb:/var/lib/mysql
